export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST'
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS'
export const USER_PROFILE_FAIL = 'USER_PROFILE_FAIL'
export const USER_PROFILE_RESET = 'USER_PROFILE_RESET'

export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST'
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS'
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL'
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET'

export const USER_UPDATE_SECURITY_REQUEST = 'USER_UPDATE_SECURITY_REQUEST'
export const USER_UPDATE_SECURITY_SUCCESS = 'USER_UPDATE_SECURITY_SUCCESS'
export const USER_UPDATE_SECURITY_FAIL = 'USER_UPDATE_SECURITY_FAIL'
export const USER_UPDATE_SECURITY_RESET = 'USER_UPDATE_SECURITY_RESET'

export const USER_LIST_REQUEST = 'USER_LIST_REQUEST'
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS'
export const USER_LIST_FAIL = 'USER_LIST_FAIL'
export const USER_LIST_RESET = 'USER_LIST_RESET'

export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST'
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS'
export const USER_DELETE_FAIL = 'USER_DELETE_FAIL'

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST'
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS'
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL'
export const USER_UPDATE_RESET = 'USER_UPDATE_RESET'

export const USER_2FA_ENABLE_REQUEST = 'USER_2FA_ENABLE_REQUEST'
export const USER_2FA_ENABLE_SUCCESS = 'USER_2FA_ENABLE_SUCCESS'
export const USER_2FA_ENABLE_FAIL = 'USER_2FA_ENABLE_FAIL'
export const USER_2FA_ENABLE_RESET = 'USER_2FA_ENABLE_RESET'

export const USER_2FA_DISABLE_REQUEST = 'USER_2FA_DISABLE_REQUEST'
export const USER_2FA_DISABLE_SUCCESS = 'USER_2FA_DISABLE_SUCCESS'
export const USER_2FA_DISABLE_FAIL = 'USER_2FA_DISABLE_FAIL'
export const USER_2FA_DISABLE_RESET = 'USER_2FA_DISABLE_RESET'

export const USER_2FA_VERIFY_REQUEST = 'USER_2FA_VERIFY_REQUEST'
export const USER_2FA_VERIFY_SUCCESS = 'USER_2FA_VERIFY_SUCCESS'
export const USER_2FA_VERIFY_FAIL = 'USER_2FA_VERIFY_FAIL'
export const USER_2FA_VERIFY_RESET = 'USER_2FA_VERIFY_RESET'